### ISSUE TITLE
Whitelist required to watch AcornTV app (British version of Netflix)

### ISSUE THREAD

**Issue by Thomas499** [anudeepND/whitelist#101]
**Whitelist Request:**
api.rlje.net

**Devices effected:**
All amazon firesticks

**Hosts list that include api.rlje.net:**
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
https://raw.githubusercontent.com/EnergizedProtection/block/master/basic/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/bluGo/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts.txt

**Effects of having list above enabled without api.rlje.net on whitelist:**
When user tries to use AcornTV app, which is a paid subscription service popular in Britain that allows the user to watch certain movies and tv shows (Very similar to Netflix), this is what comes up. There is only a blank black screen where the movies and shows should be listed. 
![image](https://user-images.githubusercontent.com/38442058/56513980-e47b8000-64e8-11e9-97c7-7457f32b36b0.png)

**Effects of whitelisting:**
![image](https://user-images.githubusercontent.com/38442058/56514007-f9581380-64e8-11e9-92ff-c28ef545de0c.png)

**Comment by anudeepND** [comment]
@Thomas499 Thanks for reporting!
