### ISSUE TITLE
Whitelist (akamai, dickssportinggoods, adobe creative cloud, instagram) update

### ISSUE THREAD

**Issue by torqu3e** [anudeepND/whitelist#102]
The following domains block the Akamai delivery network and are safe to be whitelisted. The last one is a diagnostic site used by Akamai.

```
a1599.g.akamai.net
a1767.g.akamai.net
a19.g.akamai.net
whatismyip.akamai.com
```

Whitelist dickssportinggoods (this probably triggered an adult word search "dick" but is a genuine business for outdoor equipment).

```
metrics.dickssportinggoods.com
dickssportinggoods.com

```
Adobe creative cloud, required to access their subscription based service for the whole creative cloud.

```
ns1.omtrdc.net
ns2.omtrdc.net
omtrdc.net

```
Amazes me that top level domains are added to the block lists, and even name server domains. This took me quite a bit of troubleshooting to identify the layer where the failure was.

Instagram, this breaks loading of images on IG (wife complain)

`graph.instagram.com` (graph.facebook.com is already on the optional list).

**Comment by jult** [comment]
akamai.net and akamai.com as a whole I have whitelisted, no problem with bad stuff coming from that thus far. Akamai has its own checks and policies, they do have *some* moral values, I mean, their heritage is with Tim Berners-Lee no less. https://www.akamaiaffinity.com/about-akamai

**Comment by anudeepND** [comment]
@torqu3e Which adlists are you using with your Pi-hole?

**Comment by torqu3e** [comment]
> @torqu3e Which adlists are you using with your Pi-hole?

```
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
https://raw.githubusercontent.com/HenningVanRaumle/pihole-ytadblock/master/ytadblock.txt
```

**Comment by anudeepND** [comment]
@torqu3e omtrdc.net is nasty tracking domain. I will take a closer look at akamai.net domains. Can you post the output of `pihole -q dickssportinggoods.com`?

**Comment by torqu3e** [comment]
```
$ pihole -q dickssportinggoods.com
 Match found in Whitelist
   metrics.dickssportinggoods.com
   dickssportinggoods.com
 Match found in list.0.raw.githubusercontent.com.domains:
   metrics.dickssportinggoods.com
 Match found in list.2.sysctl.org.domains:
   metrics.dickssportinggoods.com
```

I get your point about omtrdc.net though what I have been complaining about is that banning top level domains causes all records under them to be banned as well e.g. NS, MX etc. Hence suggestion to ban FQDNs instead of top levels.
