### ISSUE TITLE
whitelist CDN fraud prevention site *.forter.com and Zelle banking

### ISSUE THREAD

**Issue by RobbieTheK** [anudeepND/whitelist#105]
I made a post on [the pi-hole discourse, ](https://discourse.pi-hole.net/t/false-positives-on-swimoutlet-com-and-forter-fraud-prevention-solution-cdn-google-shopping-blocked/20163) but no-one has replied. Within a site like swimoutlet.com, they use a fraud protection service called forter.com. We also found when Google shopping a page was being blocked with the subdomain clickserve.dartsearch.net. I also posted how [Zelle within Citbank.com](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212/38?u=robbiethek) is blocked, which I'm pretty sure is *.online-metrix.net.

On a side note I've tried to white list all of the Google Play Store. I've whitelisted all of the [1-20].client-channel.google.com subdomains and [others mentioned here](https://discourse.pi-hole.net/t/pihole-still-blocking-google-play-store/7983),  as well as ssl.google-analytics.com. Installation just hangs, tried on multiple Android phones.

**Comment by anudeepND** [comment]
@RobbieTheK forter.com and its subdomains are not blocked in default blocklists. Can you paste the output of `pihole -q forter.com`?

**Comment by RobbieTheK** [comment]
> pihole -q forter.com

haps it's another domain then?
```
ihole -q forter.com
 Match found in Whitelist
   93e140b8b0e84b09ac891c94e68686d2-c74f8a20b3ca.cdn.forter.com
   c74f8a20b3ca.cdn4.forter.com
   cdn0.forter.com
   cdn3.forter.com
   cdn4.forter.com
   cdn9.forter.com
   cdn.forter.com
```

**Comment by RobbieTheK** [comment]
Here's another, landing pages from emails never redirect properly with this:
```
pihole -q trackcmp
 Match found in list.0.raw.githubusercontent.com.domains:
   trackcmp.net
 Match found in list.2.sysctl.org.domains:
   trackcmp.net

```

**Comment by anudeepND** [comment]
@RobbieTheK trackcmp.net seems to be a email tracker, so it will not be added

**Comment by RobbieTheK** [comment]
> @RobbieTheK trackcmp.net seems to be a email tracker, so it will not be added

OK that I understand but what about *.forter.com?

**Comment by anudeepND** [comment]
@RobbieTheK I will look into it, even I had some of `*.forter.com` in my Pihole log (Vox media maybe?)
