### ISSUE TITLE
You may add a few more from steam too.

### ISSUE THREAD

**Issue by tutyamxx** [anudeepND/whitelist#107]
steamcdn-a.akamaihd.net
steamcommunity-a.akamaihd.net

**Comment by anudeepND** [comment]
@tutyamxx Can you provide some info on which hostfiles are you using?

**Comment by tutyamxx** [comment]
The 2 links above, steam is using them for sharing images via chat and steam community market as well. I suggest searching "steam" on google. Basically it's the biggest digital market for PC games

**Comment by SuperSandro2000** [comment]
@tutyamxx He wanted to from which hosting file is adding this to the blacklist.

**Comment by tutyamxx** [comment]
Oh, well a lot of them, that might be the problem? Obviously added them as whitelist myself.
