### ISSUE TITLE
Make scripts executable

### ISSUE THREAD

**Issue by DukeyToo** [anudeepND/whitelist#110]
Git understands file attributes and even sees them as a change. Make the scripts executable in git so that new users don't have to manually do it

**Comment by anudeepND** [comment]
Thanks for letting me know, `git update-index --chmod=+x whitelist.sh` is this the correct flag to make it executable?

**Comment by DukeyToo** [comment]
Depending on git version and os or shell, you can just `chmod +x
whitelist.sh` and then commit the change like any other change. But what
you have seems like it would work too.

**Comment by anudeepND** [comment]
@DukeyToo Sorry for the late reply, it is been added in fb7fe3d7c28b88ec56d5768008e3e35f0541d50d
