### ISSUE TITLE
Add white listing for Amazon Kindle.

### ISSUE THREAD

**Issue by ZeroDot1** [anudeepND/whitelist#113]
Hi @anudeepND,

In a very large number of blacklists, domains for [Amazon Kindle](https://tinyurl.com/y6g9u2wm) are blocked.
This problem should be solved by putting the most important URLs on a white list.
I tested everything yesterday and the following URLs are used in Germany:

```cpp
cognito-identity.us-east-1.amazonaws.com
unagi-na.amazon.com
ocsp.rootg2.amazontrust.com
det-ta-g7g.amazon.com
todo-ta-g7g.amazon.com
device-messaging-na.amazon.com
s3-eu-west-1.amazonaws.com
us-east-1.amazonaws.com
```

**Comment by anudeepND** [comment]
@ZeroDot1 Sorry for the late reply, thanks for reporting :)

**Comment by ZeroDot1** [comment]
No problem.
Thanks for adding it to the white list.
