### ISSUE TITLE
forms.gle

### ISSUE THREAD

**Issue by pikeas** [anudeepND/whitelist#114]
Please consider adding `forms.gle` to the repo.

**Comment by anudeepND** [comment]
@pikeas Can you post the output of `pihole -q forms.gl`?

**Comment by pikeas** [comment]
```
 Match found in list.26.hosts-file.net.domains:
   forms.gle
```

I'm not sure why that list is labeled `domains`, the domain is actually blocked by https://hosts-file.net/psh.txt, which is one of the commonly recommended lists from https://firebog.net/

**Comment by anudeepND** [comment]
hosts-file.net is dead. For more info: https://www.reddit.com/r/pihole/comments/fsg11e/hostsfilenet/
