### ISSUE TITLE
Whitelist required for firestick to work properly 

### ISSUE THREAD

**Issue by Thomas499** [anudeepND/whitelist#115]
**List that blacklist the required urls** https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts.txt

**Additional Documentation of the issue** 
https://github.com/EnergizedProtection/block/issues/310

**URL's needed to be whitelisted**
```
api.amazonalexa.com 
dcape-na.amazon.com 
arcus-uswest.amazon.com
msh.amazon.com // <- Note: make a judgement call on this one. See details.
```
**Details:** 
**api.amazonalexa.com** // needed to setup a new firestick. Without it whitelisted, after you register the network name and password so that the firestick is connected to the internet, and after the first update completes, you can never finish the setup process it will get stuck on this page. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780292-ee7ee080-05ea-11ea-9636-4d4f6e853358.png">

**If api.amazonalexa.com is whitelisted** it will continue to the page that says "Your Amazon Fire TV Stick 4K is registered to (owners name) Do you want to use this account?"

Once the firestick is setup (even if it was setup on a different network then transported to the new network where api.amazonalexa.com is blocked) then the firestick appears to work properly (in my experience so far). Would never know there was a problem with this url if the room mate hadn't factory reset the firestick by mistake and I had to re-register it. **Note:** If you just de-register the firestick and re-sign back into an account, this problem doesn't happen. For the issue to occur  you have to reset to factory default or use a new firestick.

**dcape-na.amazon.com** // needed to find apps. For example, if you type in hbo go in the search bar without dcape-na.amazon.com whitelisted it will pull up Movies and TV category and Search in Apps category which doesn't list the hbo go app as shown below.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780564-56cdc200-05eb-11ea-957d-301d5e472ff3.png">

**If dcape-na.amazon.com is whitelisted** then it will additionally pull up an App and Games category where the HBO GO app is listed. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780605-6816ce80-05eb-11ea-8e17-a7bf264531d3.png">

**Note**: to repeat this issue, you must go to manage install applications and clear data for Appstore, otherwise previous searches will show up as apps and the apps you previously searched for before 
dcape-na.amazon.com was blacklisted will still show up as options to download. 

In addition, without dcape-na.amazon.com whitelisted the firestick may be the cause for on occasion pull up a screen that says "An authentication error has occurred." This particular authentication error only happened once and I believe it happened when I typed in "Starz" in the search bar to look for the app to download. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68781051-0a36b680-05ec-11ea-9046-58e8ff5ddca5.png">

Without arcus-uswest.amazon.com whitelisted the firestick will not show you your downloaded apps on the homepage where it says "recent" category and "your apps and channels" category. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780884-c774de80-05eb-11ea-8adb-33166fc67f20.png">

**arcus-uswest.amazon.com whitelisted** it shows "recent" list and "your apps and channels" list as shown below
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780985-eb382480-05eb-11ea-8f7f-41abf363947e.png">
**Note**: to repeat this issue, you must go to manage install applications and clear data for Appstore, Alexa shopping, and Prime Video.  Also, you will loose the order of your listed apps if you organized them previously. 

I also noticed without **msh.amazon.com** whitelisted, if you download an app it will get to about 90% of the download circle that shows you the status of the download and then freeze for about a minute as shown in the picture below.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/38442058/68780497-3ef63e00-05eb-11ea-910c-250c5205b200.png">
Thus, instead of a 5 second download it takes about a minute to complete. However, other than taking longer to complete downloads I haven't notice any other issues yet with msh.amazon.com blacklisted. So probably would be a good idea to figure out what msh.amazon.com does. If it provides ads or tracking then keep it on the blocklist. If it doesn't do anything bad then whitelist it so the downloads are much faster. Make a judgement call on that one.

**Comment by anudeepND** [comment]
@Thomas499 Thanks for the detailed info, I was able to get details on `api.amazonalexa.com` - https://developer.amazon.com/docs/custom-skills/request-customer-contact-information-for-use-in-your-skill.html

But there is not much info on other domains

**Comment by Thomas499** [comment]
Let me know how I can help. Here is a link https://www.reddit.com/r/pihole/comments/8bz1l1/i_blocked_a_few_amazon_domains_and_my_fire_tv/ that shows someone else ran into issues with some of the links that I mentioned but it isn't extremely helpful because the person didn't describe what symptoms each link caused when blacklisted or even confirm that each link caused a problem rather than just listing a dozen or so links that he blocked at once and realized there was a problem. 

It might be worth mentioning that yesterday I de registered a firestick and today I re-registered it. To my surprise, I found that I ran into the same issue that I previously documented for api.amazonalexa.com but even though api.amazonalexa.com was whitelisted I still ran into the same problem and found that **whitelisting ftvr-na.amazon.com** fixed the problem this time. So I am now wondering if the firestick chooses a random server from the list and if it cant connect then it won't let you register the device?

**Comment by andrewjmetzger** [comment]
I have a Fire TV Stick 4K device. For science (because science is cool) I reset it and went through the device registration process again. 

Before I began, I whitelisted these three domains as indicated by Thomas499's original comment:

```
api.amazonalexa.com 
dcape-na.amazon.com 
arcus-uswest.amazon.com
```

Device registration was completed without issue. I _did not_ have to whitelist `ftvr-na.amazon.com` as the comment above suggested. Perhaps something changed in the last month or so, but I'm guessing that Amazon might not use `ftvr-na.amazon.com` anymore; it's not showing up anywhere in my pi-hole's query logs.

Additionally, I was able to download apps almost instantly _without_ whitelisting `msh.amazon.com`; it seems the domain is no longer on EnergizedProtection's blocklist. As a suggestion, these two domains could be added to the optional list for users who have issues with their Fire TV devices after whitelisting the first three domains above.

> So I am now wondering if the firestick chooses a random server from the list and if it cant connect then it won't let you register the device?

**Comment by Thomas499** [comment]
I confirm that `ftvr-na.amazon.com` and `msh.amazon.com` are no longer on the EnergizedProtection's blocklist. Energizer has since whitelisted all of the urls that I included in this issue as I made an issue on the energizer page too as shown here EnergizedProtection/block#310 . In fact, the only url listed in this issue that I can find on any blacklist that I use now is `msh.amazon.com`  listed on https://pastebin.com/raw/8mUdqKWG I think this issue can now be closed.
