### ISSUE TITLE
Ads-blocker.com - Testing your ads blocker - still shows some ads

### ISSUE THREAD

**Issue by borzaka** [anudeepND/whitelist#120]
I still see 2 ads on this page: https://ads-blocker.com/testing/
These two:
> Do you see a banner ad above the test steps?
> Do you see any ad underneath the test steps?

I'am using today's current Pi-hole, and your whitelist.

**Comment by borzaka** [comment]
Well, I don't see any ads any more. Probably some cache. I don't know.

Maybe worth noting this link in the readme?

**Comment by anudeepND** [comment]
I think it is appropriate to mention link https://github.com/anudeepND/blacklist 
Also i didn't saw any ad on that webpage

**Comment by borzaka** [comment]
Yes, you are right, that test site should belong to your blacklist repo.
