### ISSUE TITLE
Something is wrong with the PayPal link

### ISSUE THREAD

**Issue by borzaka** [anudeepND/whitelist#121]
> We cannot process this transaction because there is a problem with the PayPal email address supplied by the seller. Please contact the seller to resolve the problem. If this payment is for an eBay listing, you can contact the seller via the "Ask Seller a Question" link on the listing page. When you have the correct email address, payment can be made at www.paypal.com.

**Comment by anudeepND** [comment]
@borzaka That's strange, anyway here's my PayPal.me link - https://www.paypal.me/anudeepnd this should work (probably)

**Comment by borzaka** [comment]
Yes, that link is working, but you are not receiving personal payments. Therefore I have to check _"Paying for goods or a service? Select the checkbox and your eligible purchases may be covered by PayPal Buyer Protection."_ and give my shipping address.

If you can, please enable personal (or donation-like) payments. I don't know the correct term, as I see the messages in hungarian (I'am from Hungary).

**Comment by anudeepND** [comment]
@borzaka according to PayPal, https://www.paypal.com/in/smarthelp/article/can-i-send-personal-payments-to-a-friend-or-relative-using-my-paypal-india-account-faq638

I have sent a DM on twitter to see if there's any other way to receive the money. I wil update you once they resolve my queries

**Comment by borzaka** [comment]
Well, it looks like you can't receive donations in India? Strange...

**Comment by anudeepND** [comment]
@borzaka PayPal has very limited features here, let's see what PayPal support will come up with

**Comment by anudeepND** [comment]
[they don't support sending / receiving money in India ](https://i.imgur.com/IZSCrYa.jpg)

**Comment by borzaka** [comment]
Oh.

I was able to send with "No address needed" option via the https://www.paypal.me/anudeepnd link.
I think you can maybe replace the old PayPal link to this new one.
After that, maybe you can close this issue.

Thx!

**Comment by anudeepND** [comment]
@borzaka Thanks for the donation :)
