### ISSUE TITLE
Add s.put.re to whitelist

### ISSUE THREAD

**Issue by tonyrulez** [anudeepND/whitelist#122]
put.re is an MD5 perfect image hosting site. `s.put.re` is the URL for hosted images, i.e. https://s.put.re/hn23ua29.png

**Comment by anudeepND** [comment]
@tonyrulez Sorry for the late reply, can you post which blocklist blocks `s.put.re`?

**Comment by antwal** [comment]
the domain s.put.re is also in malwarebytes blacklist

**Comment by anudeepND** [comment]
https://forums.malwarebytes.com/topic/251395-review-of-malware-blocks-against-some-types-of-putre-and-sputre-content/
