### ISSUE TITLE
Make it compatible with Pihole Beta 5.0

### ISSUE THREAD

**Issue by Kopernikus1979** [anudeepND/whitelist#125]
Hi,

Starting from Pihole Beta 5.0 is migrating from list storage to a database.
Link: https://pi-hole.net/2020/01/19/announcing-a-beta-test-of-pi-hole-5-0/

**Comment by mibere** [comment]
@Kopernikus1979 List maintainers don't have to change anything. They just changed the internal way of storing data, not the way the user adds lists.

**Comment by Obihoernchen** [comment]
That's not 100% true for this project as it uses scripts to update/merge the lists. Currently this script is creating a list file only. This needs to change.

**Comment by jmgb4** [comment]
I second this. I just upgraded my pi to 5.0 last night and found this script this morning =(

**Comment by brentil** [comment]
From the linked article specifically stating it does impact custom scripts.

> Custom user scripts that rely on manipulating files such as gravity.list,black.list,white.list etc. need to be migrated to interacting with the database, however, there is so much power in this new approach, it’s really really worth it! And, we’re here to help, just open a discussion on our Discourse platform and we can assist with advise how to use the new gravity database for your custom scripts.

**Comment by Obihoernchen** [comment]
To make it work with v5.0 add
```bash
pihole -w -q $(cat /etc/pihole/whitelist.txt | xargs)
```
before the `${GRAVITY_UPDATE_COMMAND} > /dev/null` line.
This should work.

**Comment by Kopernikus1979** [comment]
@Obihoernchen 

Just upgraded to Pihole 5 and edited the script like you said, and all is going fine.
Thx

@anudeepND 
Can you integrate this fix?

**Comment by brentil** [comment]
> To make it work with v5.0 add
> 
> ```shell
> pihole -w -q $(cat /etc/pihole/whitelist.txt | xargs)
> ```
> 
> before the `${GRAVITY_UPDATE_COMMAND} > /dev/null` line.
> This should work.

Will this add anything into the new comments field v5 supports or just leave it blank?

**Comment by Obihoernchen** [comment]
I guess it will leave it blank.

**Comment by anudeepND** [comment]
Sorry for the late response everyone. Currently I'm not on beta. @Obihoernchen If everything is good, I will make the change? Also is it possible to add comments to domains in the file and make it appear in user's pi-hole?

**Comment by Obihoernchen** [comment]
@anudeepND sorry but I have no Idea all I did was looking at the man page :D
I didn't test it. Still on v4 as well.

**Comment by biship** [comment]
@anudeepND FYI, you can follow this to make a beta version available:
https://support.google.com/googleplay/android-developer/answer/3131213?hl=en
We can use that version to test and get you logs etc.

Here is how to add comments with v5.0
https://discourse.pi-hole.net/t/add-comments-to-domains-on-the-cli/28556/19

**Comment by sew3521** [comment]
I can confirm that the fix by proposed by @Obihoernchen  works flawlessly. It is worth noting that this script runs a full gravity update so if you have many block lists it will take a few minutes to run. Also, if you have Gravity set to update once every 24 hours via Cronjob you might want to consider not having it run after this script runs.
@Obihoernchen  is correct in the assumption that the Comment field is blank.

Tested using the latest build as of 4/6/2020 at 11:26PM (GMT-6)
Pi-hole Version vDev (release/v5.0, v4.3.5-465-g2de5362)
Web Interface Version vDev (release/v5.0, v4.3.2-460-g3dc9290)
FTL Version vDev (release/v5.0, vDev-78e0332)

**Comment by anudeepND** [comment]
Thanks everyone, the changes has been implemented. However the comment field remains blank. I'm thinking about adding comments directly to the gravity.db using SQL queries, I will create a new PR for this feature
