### ISSUE TITLE
Microsoft Bing adresses for "Sperrbildschirm"

### ISSUE THREAD

**Issue by XxJooO** [anudeepND/whitelist#128]
Hi, I want to whitelist the Bing Servers that give me the new background pictures on the "Sperrbildschirm" of Win10 by using "Windows-Blickpunkt".

Does anyone know those addresses?

**Comment by anudeepND** [comment]
@XxJooO `https://discourse.pi-hole.net/` is a great place for discussing issues like this, happy posting!

**Comment by llacb47** [comment]
Whitelist `arc.msn.com`.
