### ISSUE TITLE
iRobot login for Roomba

### ISSUE THREAD

**Issue by grush128** [anudeepND/whitelist#129]
socialize.us1.gigya.com

is required to be whitelisted to login via the app.

https://developers.gigya.com/display/GD/socialize.login+JS

**Comment by anudeepND** [comment]
@grush128 Thanks for reporting. Can you list out the blocklists which blocks `socialize.us1.gigya.com `?

**Comment by SuperSandro2000** [comment]
It was in some list before but of today I can't find it anymore.

**Comment by grush128** [comment]
I will look for it ASAP. I should have all the block lists I used.

**Comment by SuperSandro2000** [comment]
I searched trough a compilation of a friend and there it was removed on 20. Feb https://github.com/deletescape/noads/commit/cbc28f8b290c4ac61c61170cc86d3d38aea58adc#diff-03fec5d3020c661b75efd7669fd8f18bL7855

**Comment by grush128** [comment]
Well then looks like it's no longer an issue thanks for doing the search.

**Comment by SuperSandro2000** [comment]
I think we should add it anyway. Wouldn't hurt. Maybe some list re-adds it or old lists still have it.

**Comment by scafroglia93** [comment]
socialize.us1.gigya.com blocked at the moment

**Comment by anudeepND** [comment]
Oops...it was in my host file and I  removed it in the latest update

**Comment by grush128** [comment]
From https://firebog.net/ :
Here are the lists mentioning gigya.com or some version of it.

https://v.firebog.net/hosts/AdguardDNS.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
