### ISSUE TITLE
more domains, trying to contribute

### ISSUE THREAD

**Issue by cusco** [anudeepND/whitelist#13]
Hello.

I'm not using your list. I googled for known pihole whitelists and reddit with your link came on top.

I've been running pihole for about 6 months now, with lots of black lists. We have about 100 people everyday on workstations using pihole's dns.

Time to time I need to whitelist something. 
I noticed my whitelist file is getting rather large, thus went googling for some trusted whitelist that everybody can benefit from.

All this to say: here! have my whitelist, it may help you!

[wl.txt](https://github.com/anudeepND/whitelist/files/1880163/wl.txt)

I have no structure, no comments, no optional. It was built as needed. Every time a needed site is not displaying correctly, there I go, open F12, see what links are being blocked and whitelist one by one until it works. (normally external js are the problem)

**Comment by anudeepND** [comment]
Thanks for the list @cusco, I will review it and add necessary domains to whitelist.

**Comment by Freekers** [comment]
@anudeepND I already verified them (and removed some), but feel free to look at them again :) Merge-request incoming.

**Comment by anudeepND** [comment]
@cusco I have updated the list. Also i would like to mention that most of the domains are already included in the `whitelist.txt`
