### ISSUE TITLE
Overwrite existing whitelist

### ISSUE THREAD

**Issue by Daskew78** [anudeepND/whitelist#130]
Hi,

If I install this will it overwrite my existing whitelist? Do I need to back it up first?

And will new manually added domains I personally add be okay? And will updates not overwrite my personally added domains?

Thanks.

**Comment by Obihoernchen** [comment]
No it will append entries to your existing whitelist and remove duplicates afterwards.
Your domains are kept.

**Comment by Daskew78** [comment]
Thanks for the fast reply

Kind Regards
David Askew

Mobile: 07788 316166
Email: david.askew@hotmail.co.uk

On 15 Feb 2020, at 02:22, Obihörnchen <notifications@github.com> wrote:

﻿

No it will append entries to your existing whitelist and remove duplicates afterwards.
Your domains are kept.

**Comment by notDavid** [comment]
But...

does that mean this repo can never remove items from their whitelist? These removes items would not be removed from our local whitelist when using `whitelist.sh`?

**Comment by anudeepND** [comment]
@notDavid It dosent any entries from the user whitelist.txt and a backup of the whitelist.txt will be made with the name `whitelist.txt.old`
