### ISSUE TITLE
Adobe Creative Cloud License Failure

### ISSUE THREAD

**Issue by jsprinceiii** [anudeepND/whitelist#131]
Please minimally add:
lm.licenses.adobe.com and activate.adobe.com

Creative cloud applications may require others.
More information can be found at:
https://helpx.adobe.com/enterprise/kb/network-endpoints.html

Thanks!!

**Comment by anudeepND** [comment]
@jsprinceiii Thanks for reporting, can you please provide information about the blocklists you're using?

**Comment by antwal** [comment]
i have added Adobe Cloud License on custom whitelist; but another pi-hole not have it. I believe that creating a list dedicated to domains for license management would be better than inserting it directly into a generic whitelist

**Comment by anudeepND** [comment]
@antwal It will not be added to the whitelist.txt, but if I get the info on which host file is blocking that domain, I can notify the blocklist maintainer
