### ISSUE TITLE
Add these domains to trackers whitelist

### ISSUE THREAD

**Issue by the4anoni** [anudeepND/whitelist#132]
Trackers: (Some shopping apps won't work when these are blocked)
clkde.tradedoubler.com
redir.tradedoubler.com
sc.tradetracker.net
tc.tradetracker.net
s.click.aliexpress.com
Not sure if whitelist or trackers
api.synerise.com
settings.crashlytics.com
punosy.com

**Comment by anudeepND** [comment]
@the4anoni Thanks for reporting, I need some time to verify these domains. So if you find anything interesting, please post it here

**Comment by anudeepND** [comment]
No replies since 5 months. Closing
