### ISSUE TITLE
Is it possible to make it work with dnsmasq (not pi-hole) ?

### ISSUE THREAD

**Issue by 2Belette** [anudeepND/whitelist#135]
Hi, 

I am using an alternative Linux distribution where it is difficult to install & maintain pi-hole, so I am wondering if it would be possible to use your script with a normal dnsmasq install ?
In fact, I am not using the GUI interface as I will send the logs to an elasticsearch to consume in kibana, so I am mainly only using the dnsmasq function with the ablity to block domain through addn-hosts function (I guess), so I would only need the script to update the list but I am not 100% sure so I am asking :)

many thanks

**Comment by anudeepND** [comment]
@2Belette Interesting, a quick Googling shows https://github.com/dave-kennedy/whitelist. You may need to modify the domain list and the paths which is appropriate for your dnsmasq setup
