### ISSUE TITLE
traffic.megaphone.fm

### ISSUE THREAD

**Issue by sew3521** [anudeepND/whitelist#137]
I added 'traffic.megaphone.fm' to my personal whitelist as it was needed for some podcasts to download. The log showed the block as 'traffic.megaphone.fm (blocked adserver.va3.megaphone.cloud)'

**Comment by sew3521** [comment]
Another one to whitelist for podcasts is pdst.fm

**Comment by anudeepND** [comment]
@sew3521 Can you mention the host files which blocks these domains?

**Comment by sew3521** [comment]
Sorry @anudeepND I should have thought about that.

 Exact matches for pdst.fm found in:
  - https://block.energized.pro/basic/formats/hosts 
  - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt 

It looks like traffic.megaphone.fm is not in the blacklist anymore. playlist.megaphone.fm is but I have not ran into any issues with it being blocked.
 Match found in exact whitelist
   traffic.megaphone.fm
 Match found in https://block.energized.pro/basic/formats/hosts:
   playlist.megaphone.fm

**Comment by anudeepND** [comment]
@sew3521 Thanks for the updates, regarding the `pdst.fm` I have noticed the blocklist maintainer. And playlist.megaphone.fm is mot found in the list, I searched the domain on https://app.energized.pro/ since I'm not using that host file

**Comment by sew3521** [comment]
@anudeepND thanks for the update! I have since removed the https://block.energized.pro/basic/formats/hosts blocklist from my Pi-Holes. It started to cause me headaches and made many websites unusable. Sorry if I caused undue work for you.
