### ISSUE TITLE
[request] add whitelist to to there own category when Pi-hole v5.0.

### ISSUE THREAD

**Issue by mwoolweaver** [anudeepND/whitelist#138]
Pi-hole v5.0 will ship a new feature "Group Management" that allows one to categorize User, blocklists, blacklist, whitelist and more. 

Adding the domains that are whitelisted to there own group would make managing them from a users perspective a lot easier imo.

**Comment by anudeepND** [comment]
As far as I know, they don't have commands to add entries to a particular group. But I will definitely consider it in the future.

**Comment by andmpel** [comment]
I've figured out how to modify the script to incorporate the --comment field to all the whitelist domains.

modify the whitelist.sh script and add "--comment "anudeepND/whitelist" in the following line as shown below and execute the script to have all top the whitelisted domains from the script imported with a comment of "anudeepND/whitelist"

${GRAVITY_UPDATE_COMMAND} $(cat /etc/pihole/whitelist.txt | xargs) --comment "anudeepND/whitelist" > /dev/null
