### ISSUE TITLE
Add to Whitelist for NBC Streaming App

### ISSUE THREAD

**Issue by zachg99** [anudeepND/whitelist#141]
I was having an issue where the NBC app was crashing randomly.  It showed some commercials but would still randomly crash, sometimes as commercials were about to start and sometimes just during a show.

I had to add one or both of these (I think it was the config2 entry) but the URLs don't have timestamps on them so i'm not positive which:

identity.mparticle.com
config2.mparticle.com

After I made the change just over a week ago the NBC app stopped randomly crashing.

**Comment by anudeepND** [comment]
@zachg99 That's strange, someone on the reddit post said that unblocking `geo.nbcsports.com` should be enough for NBC App to work. Can you give it a try? `*.mparticle.com` is a tracker and it's blocked in a popular [hostfile.](https://github.com/StevenBlack/hosts)

**Comment by zachg99** [comment]
Yeah, I actually already had geo.nbcsports.com in the list.  Possibly from pulling your whitelist (thanks for this list/project by the way).

Also, the app would work, and even display commercials, it's just it would crash while watching a show (generally this was in Dateline).  I wonder if it was trying to register with mparticle.com or something, failed, and that caused the app to crash.  I'm good now, maybe don't add it and if someone else has an issue they'll find this post.
