### ISSUE TITLE
Comments for Pi-hole v5

### ISSUE THREAD

**Issue by Obihoernchen** [anudeepND/whitelist#142]
Pi-hole v5 allows to add comments.
The following command is not documented yet but works ;)
See: https://github.com/pi-hole/pi-hole/commit/15a9d662ac5e1aab12a7c025a48d75971b3687f0

`pihole -w "test.com" --comment "Test comment"`

![image](https://user-images.githubusercontent.com/453508/81487825-b4249200-9261-11ea-8315-bf6b2f3d11ca.png)

I could add such functionality if there is interest.
We would just need to add comments to the `whitelist.txt` file, too.
What do you think?

**Comment by andmpel** [comment]
I've figured out how to modify the script to incorporate the --comment field to all the whitelist domains. 

modify the whitelist.sh script and add "--comment "whitelist.txt" in the following line as shown below and execute the script to have all top the whitelisted domains from the script imported with a comment of "whitelist.txt"

`${GRAVITY_UPDATE_COMMAND} $(cat /etc/pihole/whitelist.txt | xargs) --comment "whitelist.txt" > /dev/null`

**Comment by eTaurus** [comment]
> 
> 
> Pi-hole v5 allows to add comments.
> The following command is not documented yet but works ;)
> See: [pi-hole/pi-hole@15a9d66](https://github.com/pi-hole/pi-hole/commit/15a9d662ac5e1aab12a7c025a48d75971b3687f0)
> 
> `pihole -w "test.com" --comment "Test comment"`
> 
> ![image](https://user-images.githubusercontent.com/453508/81487825-b4249200-9261-11ea-8315-bf6b2f3d11ca.png)
> 
> I could add such functionality if there is interest.
> We would just need to add comments to the `whitelist.txt` file, too.
> What do you think?

Do you mean to comment each entry with information why it needs to be whitelisted? IMO a good idea if there where more space for the comment field. As of now not much of the information would be readable without scrolling sideways. This would demand changes in Pi-hole itself. And a hell of a lot of manual work with the "whitelist.txt"!
For to make it easier to differentiate between manually entered entries and entries added by this script each entry should contain a pointer to where it came from, "anudeep" for example.

**Comment by anudeepND** [comment]
@Obihoernchen @andmpel @eTaurus Take a look at the upcoming update. I have added comment for every domain in the whitelist.txt. Check out the [whitelist-2.0](https://github.com/anudeepND/whitelist/tree/whitelist-2.0) branch to test the new scripts.

**Comment by eTaurus** [comment]
Great update! Donation on the way!
Must have been a pain to add comments to all of the entries but: No pain,
no gain!

Regards,

Benjamin

Am Sa., 29. Aug. 2020 um 18:45 Uhr schrieb Anudeep <notifications@github.com

**Comment by andmpel** [comment]
Can't wait to test it out! Thanks!
