### ISSUE TITLE
Please add connectivity check URLs to whitelist

### ISSUE THREAD

**Issue by schuettecarsten** [anudeepND/whitelist#144]
Please add these connectivitycheck URLs to the whitelist, just to make sure that they are not blocked somewhere else accidentially. These URLs are used by mobiles devices to check internet connectivity:

- www.msftconnecttest.com
- www.msftncsi.com / dns.msftncsi.com

Reference: 
https://support.microsoft.com/en-us/help/4494446/an-internet-explorer-or-edge-window-opens-when-your-computer-connects, Section "NCSI active probes and the network status alert"

- connectivitycheck.gstatic.com
- connectivitycheck.android.com

Reference:
http://androidxref.com/6.0.0_r1/xref/frameworks/base/packages/CaptivePortalLogin/src/com/android/captiveportallogin/CaptivePortalLoginActivity.java (Line 59)

- clients3.google.com

Reference:
http://androidxref.com/4.4.4_r1/xref/frameworks/base/core/java/android/net/CaptivePortalTracker.java (Line 64)

**Comment by anudeepND** [comment]
@schuettecarsten sorry for the late reply. These domains will be added in the next update.

**Comment by anudeepND** [comment]
clients3.google.com, www.msftncsi.com and dns.msftncsi.com were already in the list. I have added the remaining domains in the latest update.
