### ISSUE TITLE
Removing the whitelist 

### ISSUE THREAD

**Issue by SamboMambo** [anudeepND/whitelist#151]
i added this to my pi, but i whitelisted many things i do not want to whitelist, how to remove completely, and not just by deleting the domains from the pi

**Comment by SuperSandro2000** [comment]
https://discourse.pi-hole.net/t/bulk-deletion-of-blacklist-whitelist-entries/32925/2?u=supersandro2000

**Comment by MatthewFBullock** [comment]
Script linked to doesn't remove any blacklists for me. Any thoughts?
