### ISSUE TITLE
Add `tracking.dpd.de`

### ISSUE THREAD

**Issue by notDavid** [anudeepND/whitelist#155]
Hi there, please consider adding `tracking.dpd.de` to the whitelist. It is used to see where your packages are, and blocked by https://github.com/mmotti/pihole-regex/blob/master/regex.list#L15

Thank you!

**Comment by mmotti** [comment]
I'm considering removing this particular regexp as there are a lot of false positives.

Could still be useful for those who don't check back and update the regexp list though.
