### ISSUE TITLE
(Re)moving domains (to other lists) doesn't remove them from Pi-hole's whitelist

### ISSUE THREAD

**Issue by Freekers** [anudeepND/whitelist#16]
In commit 6f2a16c you moved some domains to another list, but the current bash-script doesn't remove these domains from Pi-hole. 

I know this is hard to implement but I think this is something to take into account when adding/removing domains ;)

Kind regards.

**Comment by anudeepND** [comment]
Most of the domains are moved to another list due to Facebook scandal (except link shorteners).
By the way do you have any other whitelisted domains other than this list?

**Comment by Freekers** [comment]
Thanks for your reply.
I only use your whitelist.txt and my personal whitelist.txt in my fork of your repo.

**Comment by Freekers** [comment]
True 👍
