### ISSUE TITLE
"Python3" needed before directory of whitelist.sh

### ISSUE THREAD

**Issue by Down200** [anudeepND/whitelist#160]
Line 117 gives an error when run. Putting "python3" in-between "sudo" and "whitelist/scripts/whitelist.py" fixes the issue. Not sure if line 112 would be able to successfully execute due to this same issue.

**Comment by anudeepND** [comment]
@Down200 Thanks for reporting. I also changed the permission of both the files to make them executable in b25ac3665de5a61f768425b46f4d38ad4b9f5bb0

**Comment by Down200** [comment]
Thanks! This fixed the issue!
