### ISSUE TITLE
JsDelivr

### ISSUE THREAD

**Issue by realizelol** [anudeepND/whitelist#174]
Hi anudeepND,

it's jsdelivr.com not jsdelivr.net

https://www.jsdelivr.com/

best regards
realizelol

**Comment by jimaek** [comment]
jsdelivr.com is the website
jsdelivr.net is the domain serving the content.
So both should be whitelisted for everything to operate normally.

**Comment by realizelol** [comment]
Ah, ok thank you.

There's just no A or AAAA entry. But for example there's a SRV and a TXT entry.

best regards
realizelol
