### ISSUE TITLE
error message since yesterday (?), failed to insert domains....

### ISSUE THREAD

**Issue by TillAtHome** [anudeepND/whitelist#175]
I get an error message when i run whitelist.py

[X] Failed to insert domains into Gravity database near "(": syntax error

**Comment by anudeepND** [comment]
This error is due to the latest update which changed the SQL query format.

 Follow these steps: 
1. Run the `uninstall.py`
2. `git clone https://github.com/anudeepND/whitelist.git`
3.  `sudo python3 whitelist/scripts/whitelist.py`

This should work

**Comment by TillAtHome** [comment]
thx for your help. the script is working again.
