### ISSUE TITLE
Rename repo to allow-list?

### ISSUE THREAD

**Issue by OmgImAlexis** [anudeepND/whitelist#176]
In keeping up with https://github.com/github/renaming it'd be nice to have this repo and https://github.com/anudeepND/blacklist updated to be allow-list and deny-list respectively.

Since GitHub will forward the old names over this shouldn't be much of a chance nor should I cause any issues for users.

**Comment by SuperSandro2000** [comment]
As long as pihole is still using white- and blacklist I wouldn't rename the repo.

**Comment by OmgImAlexis** [comment]
Okay, so I’ll go and open a request with them to do the same. Once that’s done you’ll be fine renaming these?

**Comment by SuperSandro2000** [comment]
I wouldn't mind but I can't decide that.

**Comment by geeknik** [comment]
GitHub virtue signaling will save the world 🤣🤣🤣

**Comment by OmgImAlexis** [comment]
What do you mean? 🤔

**Comment by anudeepND** [comment]
Please refer This has been already discussed - https://github.com/anudeepND/blacklist/issues/112

**Comment by OmgImAlexis** [comment]
Changing the name wouldn’t cause any issue as the redirect works. Changing the branch would but I’m sure GitHub is going to address that later this year when they add the migration tools in.

**Comment by markusdresch** [comment]
but it also wouldn't make any sense. look up "blacklist" and "whitelist" in a dictionary. those are real words. "block-list" and "deny-list" are made up substitutes that noone in the tech community (apart from some twitter bubble echo chambers) ever used, so this is counterproductive.

**Comment by anudeepND** [comment]
The term 'master' does not refer to or imply racism. 'Master' can mean lots of things, and terms such as 'whitelist' and 'blacklist' have been in the tech world for a long time. I don't like the idea of comparing it to a particular community. These terms has been industry standard for quite some time.

As @spirillen said in an older post, many RFC-standards are using white/black-list and they will remain as it is. 

Changing these terms does not prevent racism or improve the workplace culture for colored people. And the word master is present in Master's Degree, MasterCard an Master of Science etc. changing these terms does not make any sense.

**Comment by OmgImAlexis** [comment]
So in other words “go away we don’t care”. Glad we got that sorted.

It’s honestly sad that you’d rather sit here and explain why this isn’t a problem instead of just changing the name. Really shows your priorities towards your users. 💁‍♀️

**Comment by OmgImAlexis** [comment]
I’ll be opening RFCs to change those existing projects over too. So I guess I’ll be able to force your hand that way then. So be it.

**Comment by markusdresch** [comment]
you are totally free to fork a project and name it anything you like, be it pink-unicorn-list or omgi-male-xis-list (could you change your name to something more inclusive please?). you are totally not free to force your opinion on anyone else, your mindset is very disturbing and reminds me of the darkest times in human history.

anyway, issues like this are totally off-topic as they do nothing to improve code quality, they do not fix bugs or request features, they are just personal opinion, divisive and disruputive, bringing in politics and ideology where it shouldn't be.

**Comment by SuperSandro2000** [comment]
> bringing in politics and ideology where it shouldn't be.

Open source is full of politics but a lot of times in the direction of privacy.

**Comment by spirillen** [comment]
It is so sad to see how people reject knowledge for the sake of there own deception of how things is related.

As @anudeepND already mentioned and link to, this topic has already been enlightened with knowledge an the relation of the naming. The knowledge have been spooked.

To @OmgImAlexis I'll like to see you have all the RFC's <https://github.com/anudeepND/whitelist/issues/176#issuecomment-697923269> changed, you'll be up against knowledge from the dawn of the bit of why the naming was chosen.

As a "thinking out loud"
Q: Wonder what the naming is in a computer cluster (aka cloud, to make it more likeable for the unknowing) like what GH, FB, and other big infrastructure in distributed on...??
A: Hmm (multi-)master and slaves :smiley: !!

Keep taking things out of contents, is not going to help anybody, actually, sadly only quiet the opposed and keeping people in the dark.

But would it be OK to call these kinds of lists as: red-, green-, yellow-, blue-, dark-list? or are these colors also racism?
