### ISSUE TITLE
fast.fonts.net

### ISSUE THREAD

**Issue by derralf** [anudeepND/whitelist#178]
Hi, please consider adding fast.fonts.net to the whitelist.
It is used to deliver webfonts.
It is blocked by https://v.firebog.net/hosts/static/w3kbl.txt

**Comment by anudeepND** [comment]
It is maintained by @WaLLy3K, can you look into it?

**Comment by WaLLy3K** [comment]
Thanks for bringing it to my attention @anudeepND, that entry's been removed.
