### ISSUE TITLE
Only supports default group

### ISSUE THREAD

**Issue by spacepost** [anudeepND/whitelist#179]
The group id appears to be hard coded to 1 in the sql file. It would be nice if group name or id could be supplied as a parameter to the install.

**Comment by anudeepND** [comment]
The `1` means that the domain is enabled, Pi-hole [docs ](https://docs.pi-hole.net/database/gravity/) has some information about the database. But it would be nice if we can use the Group management, I will think about how to implement it

**Comment by mwoolweaver** [comment]
> I will think about how to implement it

@anudeepND I think I have this figured out. Will submit a P/R that accomplishes this soon.
