### ISSUE TITLE
Bing Maps Platform / Virtual Earth

### ISSUE THREAD

**Issue by PurpleHullPeas** [anudeepND/whitelist#18]
I had to whitelist dev.virtualearth.net in order to select a store location on costco.com. It appears to be related to Bing maps. I found it blocked in the WIndowsSpyBlocker list along with a few other Virtual Earth domains that may need to be unblocked as well.

dev.virtualearth.net
ecn.dev.virtualearth.net
t0.ssl.ak.dynamic.tiles.virtualearth.net
t0.ssl.ak.tiles.virtualearth.net

**Comment by anudeepND** [comment]
@PurpleHullPeas Thanks for reporting. All 4 domains are added to list
