### ISSUE TITLE
Google domains

### ISSUE THREAD

**Issue by iteqla** [anudeepND/whitelist#185]
**lh3.googleusercontent.com**  This is needed to view profile pictures in Gmail, participants in Google Meet sessions and other application of the G Suite

**mail-attachment.googleusercontent.com**   If this is blocked, it is not possible to download attachments from Gmail

**googlehosted.l.googleusercontent.com**  This is needed to view icons on Gdrive

**Comment by anudeepND** [comment]
Thanks for reporting, what is the output of `pihole -q` ?

**Comment by iteqla** [comment]
**pihole -q googleusercontent** returns the below. Please let me know if you need a more specific domain

 **Match found in exact whitelist**
   lh3.googleusercontent.com
   mail-attachment.googleusercontent.com
   googlehosted.l.googleusercontent.com
 **Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:**
   displayads-formats.googleusercontent.com
   affiliate.googleusercontent.com
 **Match found in https://adaway.org/hosts.txt:**
   displayads-formats.googleusercontent.com
 **Match found in https://v.firebog.net/hosts/Admiral.txt:**
   184.48.190.35.bc.googleusercontent.com
   202.90.190.35.bc.googleusercontent.com
   246.39.190.35.bc.googleusercontent.com
   42.219.186.35.bc.googleusercontent.com
   49.74.190.35.bc.googleusercontent.com
   64.98.201.35.bc.googleusercontent.com
   84.249.186.35.bc.googleusercontent.com
 **Match found in https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt:**
   ads-icl.googleusercontent.com

**Comment by iteqla** [comment]
Hi,
is there any update on this issue?

**Comment by fabianski7** [comment]
> Hi,
> is there any update on this issue?

try to report this to the list maintainers where the domains were found

**Comment by iteqla** [comment]
> try to report this to the list maintainers where the domains were found

I'm not sure I understand your comment. They are called **Anudeep's Lists** so I thought that Anudeep was the maintainer of the list and that here wass the place to report those issues...
Am I getting something wrong?

**Comment by fabianski7** [comment]
if you think the domains are legitimate, then you should report to the maintainer of the list they are on. That way more people will benefit from this improvement.

I use all the lists that are in your log and none of them are blocking these domains. I don't know why it would be necessary to add.

If you don't agree, do whatever shit you think is best.

**Comment by iteqla** [comment]
First, there is no need for that language.
Second, what I think is best is exactly what I am doing, which is reporting legitimate website so that they can be added to the whitelist. The whole point of a whitelist is to prevent false positives, as opposed to go on every single blocklist. The reason is because the exact matches can be adjusted directly from the blocklist, as you suggest, but the expressions are not.

Besides, this si from the Pi-Hole official dicumentation:
_The more blocklists you add, the more likely you'll come across a false positive. First, you'll want to check out Commonly Whitelisted Domains over at the Pi-hole forum, followed up by anudeepND's curated whitelist, and then you can see if anything below is relevant to your interests._

So is this whitelist still curated or not?

**Comment by iteqla** [comment]
Legit websites have been removed from the list. Thanks.
