### ISSUE TITLE
Facebook Content Delivery Network

### ISSUE THREAD

**Issue by PurpleHullPeas** [anudeepND/whitelist#19]
I had to whitelist this domain in order to download a pdf attachment from Facebook messenger.
cdn.fbsbx.com

Initial Googling of the domain screams "virus," but I'm not so sure that's the case.

**Comment by anudeepND** [comment]
This domain is related to Facebook, can I know in which adlist it's been included?

**Comment by anudeepND** [comment]
Since it's a Facebook domain, it will not be included in `whitelist.txt` instead it will be in `optional-list.txt`. 
Thanks for reporting!
