### ISSUE TITLE
Disney + and TV now 

### ISSUE THREAD

**Issue by Marcopolox13** [anudeepND/whitelist#205]
I have problems with Disney+ and TV now Germany. There are blocked domains, witch stops playing. I can't detain with exactly domains.

**Comment by anudeepND** [comment]
@Marcopolox13 can you provide me with more info so that I can reproduce the issue and can you post all the domains that are being blocked while using Disney+?

**Comment by Marcopolox13** [comment]
Hey, thx for replay, but like I said before I can detain the blocks urls. At the moment I have no problems with these services.
