### ISSUE TITLE
an email-whitelist functionality have a link?

### ISSUE THREAD

**Issue by StefanL38** [anudeepND/whitelist#206]
Hello,

while googling for Email-whitelist-functionalities I came across your GitHub Whitelist-repo.
I aplogise that this message isn't a "whitelist"-issue about **your** software.

What I'm looking for is a **super-hyper-radical** whitelist-functionality for email:

All and every email that is **not** listed on my whitelist shall be rejected full-automatic with an answering message like this

"Your Email has been automatically deleted. Use the following link to autorise yourself as a real human beeing ......................
Or use another way of contacting the person with this emailadress to obtain permission for email-delivering to this person.

Whenever I **send** an email to anybody this emailadress shall be added automatically to the whitelist.

I know I will disapoint some people but I'm not based on marketing. So I don't care if some people that I don't know yet don't reach me and "walk away"

So a Raspberry Pi should act as a gateway where all incoming and outgoing email must pass through. 

If you happen to know such a software or a ready to use tutorial to configure what Raspi-Software ever please post a link.

best regards Stefan

**Comment by anudeepND** [comment]
@StefanL38 Sorry, I don't have much info about what you are looking for. Try posting this issue on reddit or Raspberry Pi Forum
