### ISSUE TITLE
kinesis.us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by brianp9906** [anudeepND/whitelist#208]
Please white list kinesis.us-east-1.amazonaws.com or remove blocking from it. 

For example Canvas (education software) uses it to save student answers.

**Comment by anudeepND** [comment]
@brianp9906 can you provide me with more info? Which blocklists are you using? And where it's blocked

**Comment by brianp9906** [comment]
I was using https://github.com/anudeepND/blacklist which is what’s noted by NextDNS on their portal. I had too many problems with it so I stopped using it and it fixed my issue. 
Unfortunately I don’t have more info since it was 9 months ago. 

Anudeep's Blacklist
A list of adserving and tracking sites maintained by me. This list will be updated frequently.
github.com/anudeepND/blacklist

**Comment by anudeepND** [comment]
@brianp9906 Thanks for the input. That list is maintained by me, I will remove it in the next update
