### ISSUE TITLE
Blocking GTAOnline Telemetry crashes the game

### ISSUE THREAD

**Issue by MainFighter** [anudeepND/whitelist#22]
Blocking this domain seems to be crashing GTAOnline on **PC** since March, unblocking the domain fixed it for people at [GTAForums](https://gtaforums.com/topic/907162-crashing-after-new-updates/) and my mates plus myself.

`prod.telemetry.ros.rockstargames.com`

It is in [NoTrack](https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt) from https://firebog.net/.

**Comment by anudeepND** [comment]
@MainFighter Thanks for the info. I have included it in the `optional-list.txt`
