### ISSUE TITLE
Are the allow lists still maintained?

### ISSUE THREAD

**Issue by timkgh** [anudeepND/whitelist#220]
They haven't been updated in over a year, they could use some new entries, e.g.

`goto.target.com`  CNAME  for `goto-target-com.customtraffic.impactradius.com`

**Comment by anudeepND** [comment]
Sorry for the late reply everyone. The project is still alive and I will be actively maintaining it from now on. 

`*.impactradius.com` is a tracker and will not be added to the list. 
For more info:
https://whotracks.me/trackers/impact_radius.html 
The domain is also blocked in https://github.com/StevenBlack/hosts, a well known host aggregator

**Comment by timkgh** [comment]
I understand it is a tracker at some level, but it's used by big shopping sites such as target.com, walmart.com/jet.com to send links in shopping confirmation emails. The list is not useful if it breaks legit emails or shopping sites or legit referral links.

FWIW, these links are allowed by NextDNS for example:
https://github.com/nextdns/metadata/blob/master/privacy/affiliate-tracking-domains#L303

NextDNS has this to say about the links:
> Allow Affiliate & Tracking Links
> Allow affiliate & tracking domains common on deals websites, in emails or in search results. Those usually only get called after manually clicking on a link.

**Comment by anudeepND** [comment]
I can add it to the referral-list.txt, these domains are application / site specific issues.
