### ISSUE TITLE
Epic Games friends list broken with latest Fortnite Season

### ISSUE THREAD

**Issue by derekpurdy** [anudeepND/whitelist#223]
You need to whitelist epic games now to get the friends list to work in game, atleast with xbox.

Example for regex

(\.|^)epicgames\.com$

**Comment by anudeepND** [comment]
@derekpurdy Do you have any specific domains to make friends list work?

**Comment by derekpurdy** [comment]
Unfortunately I didn't have any more information, I just came across that on reddit as the fix. My kids were desperate to fix the issue so I made it work.
