### ISSUE TITLE
Fix "blocked" search suggestions on YouTube

### ISSUE THREAD

**Issue by kyle95wm** [anudeepND/whitelist#24]
When typing into YouTube, search suggestions usually pop up as you're typing. Unfortunately, a lot of block lists (two of them from Wally's site actually) has 

> clients1.google.com

In the list. While I'm sure there is more to this domain, one of its functions is search suggestions. Feel free to add this one to the optional lists (or global ones) if you wish.

**Comment by anudeepND** [comment]
Thanks @kyle95wm Its is now added to default `whitelist.txt`
