### ISSUE TITLE
secure.avangate.com is been blocked but needed for secure payments

### ISSUE THREAD

**Issue by TRaSH-** [anudeepND/whitelist#25]
pihole -q secure.avangate.com
 Match found in Whitelist (_Added it manually now because needed to do payment_)
   secure.avangate.com
 Match found in list.49.tspprs.com.domains:
   secure.avangate.com

I think i got this block list from
https://github.com/StevenBlack/hosts

**Comment by anudeepND** [comment]
Thanks @TRaSH- It is now added to `whitelist.txt`
