### ISSUE TITLE
Whitelist s.youtube.com & video-stats.l.google.com

### ISSUE THREAD

**Issue by ashleymavericks** [anudeepND/whitelist#254]
Whitelist these two domains for proper functioning of YouTube history feature.

**Comment by bbhtt** [comment]
They are already in the whitelist?

https://github.com/anudeepND/whitelist/blob/30c75868f56a4d46b3cf164e184cd888ee254fe2/domains/whitelist.txt#L132

https://github.com/anudeepND/whitelist/blob/30c75868f56a4d46b3cf164e184cd888ee254fe2/domains/whitelist.txt#L162

**Comment by ashleymavericks** [comment]
Thanks for pointing that out.
