### ISSUE TITLE
No python3 support in sandbox system

### ISSUE THREAD

**Issue by LeandroSQ** [anudeepND/whitelist#261]
Just sharing this as it may help someone, if you are restrained of using python and installing is not an option (e.g using TrueNAS shell to interact with the docker container), you can `git clone` the repo (to /tmp in this example) and run the following one-liner:

```sh

while IFS= read -r line; do [ -n "$line" ] && pihole -w "$line"; done < /tmp/whitelist/domains/whitelist.txt
```

It will map each line from the `whitelist.txt` to a pihole -w command.

**Comment by ygx0** [comment]
This worked great, thanks.
