### ISSUE TITLE
Synology.com

### ISSUE THREAD

**Issue by mc9662** [anudeepND/whitelist#27]
Hi, please can you add www.synology.com to the whitelist - needed for Synology NAS

Match found in https://v.firebog.net/hosts/Airelle-trc.txt:
www.synology.com

Thanks

Matt

PS Love your work - appreciated

**Comment by anudeepND** [comment]
@mc9662 Thanks for reporting. Glad to know that you like this project :)
This doamin is now added to `whitelist.txt`
