### ISSUE TITLE
Additional domains suggestions

### ISSUE THREAD

**Issue by nikmanzotti** [anudeepND/whitelist#3]
Hi there!

I've used your whitelist as a starting point to be customized, thanks for it!

I've found those additions as quite useful in my environment (generic services, MS Office 365 related domains, plugins and cdns used by many websites), maybe they are useful also to others.

Thanks!
Nicolò

google.com
yahoo.com
microsoft.com
skype.com
uservoice.com
linkedin.com
reddit.com
vimeo.com
youtube.com
pinterest.com
facebook.com
wordpress.com
wp.com
github.io
github.com
bing.com
wikipedia.org
facebook.net
fbcdn.net
t.co
twimg.com
gstatic.com
google-analytics.com
googletagmanager.com
googlesyndication.com
googleadservices.com
office.com
office.net
microsoftonline.com
onedrive.com
outlook.com
sharepoint.com
live.com
onmicrosoft.com
onestore.ms
gfx.ms
sfx.ms
aspnetcdn.com
s-microsoft.com
office365.com
microsoftonline-p.com
msocdn.com
akamaihd.net
akamaized.net
jquery.com
crisp.chat
tawk.to
drift.com
driftt.com
intercom.io
leadchampion.com
trialfire.com
amazonaws.com
imgix.net
sumome.com
sumo.com
bufferapp.com
filament.io
sharethis.com
addthis.com
unsplash.com
cloudfront.net
criteo.net
criteo.com
hotjar.com
onesignal.com
getsitecontrol.com
jsdelivr.net
openx.net

**Comment by anudeepND** [comment]
@nikmanzotti Thanks for the feedback, it's not a good idea to add openx.net and Google analytics to default white-list file. I will add them in another file called `optional-list`
