### ISSUE TITLE
https://www.ucas.com/

### ISSUE THREAD

**Issue by mc9662** [anudeepND/whitelist#30]
Hi @anudeepND 

https://www.ucas.com/ is the UK University application website, and track.ucas.com is the section for students to follow their application.

It matches the regex.list entry ^track(ers?|ing)?[0-9]*[-.] by https://github.com/mmotti/pihole-regex that I've implemented.
Thanks
Matt

**Comment by anudeepND** [comment]
@mc9662 Thanks for the info and your regex list, been using it for a while. So far so good :)
