### ISSUE TITLE
ocsp.apple.com

### ISSUE THREAD

**Issue by rlex** [anudeepND/whitelist#36]
Found in https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts (on first block of v.firebog.net)

This is not tracking, but https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol server

**Comment by anudeepND** [comment]
@rlex Thanks for the information. There is already `oscp.apple.com` present in `whitelist.txt`. Are `oscp.apple.com` and `ocsp.apple.com` different domains?

**Comment by rlex** [comment]
That's weird. I saw ocsp (not oscp) in blocked domains, now it just doesn't resolve to anything. I do not have access my home notebook right now, so i'll verify it a bit later.

**Comment by anudeepND** [comment]
I think the domain `ocsp.apple.com` is a legit one, because
`ping oscp.apple.com` yields an error 
`ping: oscp.apple.com: Name or service not known`

But `ping ocsp.apple.com` resolves to
`sgsin3-vip-bx-001.aaplimg.com`

I don't have any Apple devices so can you please verify?

**Comment by rlex** [comment]
Yeah, i was thinking same way. Here is entry from pihole: 
<img width="462" alt="screen shot 2018-08-21 at 6 41 18 pm" src="https://user-images.githubusercontent.com/84462/44412567-eb28b080-a571-11e8-8aeb-3d8a9834713a.png">

wasn't able to find oscp.apple.com in any sources, apart from couple of reddit threads.

**Comment by anudeepND** [comment]
@rlex I added `ocsp.apple.com` and removed `oscp.apple.com`
