### ISSUE TITLE
bethesda.net

### ISSUE THREAD

**Issue by mc9662** [anudeepND/whitelist#40]
bethesda.net is incorrectly blocked on this list
Match found in https://raw.githubusercontent.com/CHEF-KOCH/Canvas-fingerprinting-pages/master/Canvas.txt:

Bethesda is a legit gaming company - https://en.wikipedia.org/wiki/Bethesda_Softworks

I think that beth**se**da.net is the domain that should be blocked instead (s and e transposed)?

Thanks

Matt

**Comment by anudeepND** [comment]
@mc9662 Thanks for pointing it out. I have filed an [issue](https://github.com/CHEF-KOCH/Canvas-fingerprinting-pages/issues/2). If he did not take any action, I will add this domain to whitelist.txt

**Comment by anudeepND** [comment]
@mc9662 The owner if that repo didn't respond to my issue, by the way that host file has not been updated in a year. I would not recommend using it because most of the domains will bw included in other host files.
