### ISSUE TITLE
Samsung Smart TV Prime Video

### ISSUE THREAD

**Issue by PurpleHullPeas** [anudeepND/whitelist#44]
https://www.reddit.com/r/pihole/comments/9fmudp/getting_prime_video_to_work_with_samsung_smart_tv/

According to that Reddit post, the following URL needs to be whitelisted for Samsung TV's Amazon Prime Video app.
time.samsungcloudsolution.com

**Comment by anudeepND** [comment]
@PurpleHullPeas Thanks :)
