### ISSUE TITLE
ota-downloads.nvidia.com

### ISSUE THREAD

**Issue by rlex** [anudeepND/whitelist#45]
Hello, requesting addition:
```
ota-downloads.nvidia.com
```
Without it, nvidia shield tv (and probably other nvidia devices) can't download updates.

**Comment by anudeepND** [comment]
@rlex where does this domain come from? In which adlist it is present?

**Comment by rlex** [comment]
https://github.com/CHEF-KOCH/CKs-FilterList/raw/master/Ad%20%26%20Tracker/CK's-Ad%20%26%20Tracker-FilterList.txt

**Comment by anudeepND** [comment]
@rlex I have added it to `optional-list.txt`. Also I have created an issue on CHEF-KOCH's repo. Thanks for reporting.

**Comment by CHEF-KOCH** [comment]
`ota-downloads.nvidia.com` is also used to fingerprint you, places a cookie on your PC and that's the reason why it is blocked in my list(s).

**Comment by anudeepND** [comment]
@CHEF-KOCH Thanks for the information. Closing...
