### ISSUE TITLE
Adult Swim Videos

### ISSUE THREAD

**Issue by PurpleHullPeas** [anudeepND/whitelist#46]
I had to whitelist the following domain in order to watch videos on the Amazon Firestick Adult Swim app:
amd.cdn.turner.com

It is blocked in one of the default pi-hole lists:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

**Comment by PurpleHullPeas** [comment]
@anudeepND Good catch. The one domain I mentioned was the only one required to make the videos play on the FireTV app, but when I went to the desktop site adultswim.com, it was completely scrambled/broken. Adding the following made the desktop site work:

pmd.cdn.turner.com
i.cdn.turner.com
s.cdn.turner.com
z.cdn.turner.com

Some thumbnails are still blank, but other than that, it functions.

**Comment by lightswitch05** [comment]
Just to be clear, some of those domains are very clearly for ads:

```
https://z.cdn.turner.com/ads/adfuel/ais/as-ais.min.js
https://z.cdn.turner.com/ads/as/adfuel.min.js
https://z.cdn.turner.com/adultswim/.element/js/3.0/jsmd-adbp.js
https://i.cdn.turner.com/ads/as/as_homepage.js
https://i.cdn.turner.com/adultswim/big/img/footer/ad-choices.png
```

**Comment by lightswitch05** [comment]
And it looks like the domain that the website needs the most is `z.cdn.turner.com` - which is the majority of the ad content.

**Comment by PurpleHullPeas** [comment]
When I get back home I can look into it more to see if adultswim.com works without the i and z domains. The domain in the OP was all that was required for videos in the FireTV app to work, but the video thumbnails were still broken.

**Comment by PurpleHullPeas** [comment]
adultswim.com ends up looking pretty broken with both z.cdn.turner.com and i.cdn.turner.com blocked. It looks like this may be another case of the ads being served from the same domain as the content - in which case they probably belong in optional-list.txt.

**Comment by lightswitch05** [comment]
I've been thinking about this, and it looks like subdomains of 'cdn.tuner.com' is too aggressive. I'm going to move it to my aggressive list
