### ISSUE TITLE
Blocking feeds.feedburner.com breaks some podcasts

### ISSUE THREAD

**Issue by lightswitch05** [anudeepND/whitelist#47]
Hello,

I noticed today that one of my podcasts has not been updated in some time. Looking into it more it seems that it was unable to contact the server. After whitelisting `feeds.feedburner.com`, the podcast was able to update again. Perhaps this is a false positive?

**Comment by anudeepND** [comment]
@lightswitch05 Good catch, I think it's a false positive. This is what the feedBurner description says:
`
FeedBurner is a web feed management provider launched in 2004. FeedBurner provides custom RSS feeds and management tools to bloggers, podcasters, and other web-based content publishers.
`
