### ISSUE TITLE
static.chartbeat.com for www.nos.nl

### ISSUE THREAD

**Issue by pe0mot** [anudeepND/whitelist#51]
HI 
To see video's on news site www.nos.nl we need static.chartbeat.com as whitelisted.

Thanks for the good work!
Jack

**Comment by anudeepND** [comment]
@pe0mot are you sure that `static.chartbeat.com`? Because I was able to play the video with `static.chartbeat.com` blocked. I was able to play all the videos in [this](https://nos.nl/artikel/2253494-kabinet-gaat-dividendbelasting-heroverwegen.html) page.

**Comment by pe0mot** [comment]
Yep, you are right. Forget this issue.
Firefox is behaving with it's own free will. 
On this moment testing tot see what's the cause.
