### ISSUE TITLE
ae01.alicdn.com

### ISSUE THREAD

**Issue by tonyrulez** [anudeepND/whitelist#54]
The above domain is responsible for all the images on aliexpress.com. Before whitelisting it, I couldn't see any image, after that all image appeared.

**Comment by pahakalle** [comment]
Is the domain img.alicdn.com used anywhere?

**Comment by anudeepND** [comment]
@tonyrulez Can confirm. `ae01.alicdn.com` is responsible for product images. But it's not blocked in default blacklist. Can you please mention the host files you are using?

**Comment by tonyrulez** [comment]
No, I can't find img.alicdn.com used on any page.

There was a question but got deleted: "But it's not blocked in default blacklist. Can you please mention the host files you are using?"
Anyway, the answer is that I have 41 blocklists in use but can't find ae01.alicdn.com in any of them. Maybe they found the problem and pulled it from the list. But I'm sure I didn't block it manually (haven't blocked anything manually yet) so it was in there somewhere.

**Comment by anudeepND** [comment]
@tonyrulez I will look into it. Thanks for reporting

**Comment by kyle95wm** [comment]
@anudeepND it's in this list:

https://hostsfile.org/Downloads/hosts.txt

**Comment by anudeepND** [comment]
@kyle95wm Good find, @tonyrulez Thanks for reporting. Closing...
