### ISSUE TITLE
res.cloudinary.com

### ISSUE THREAD

**Issue by mc9662** [anudeepND/whitelist#56]
The site res.cloudinary.com is used for image distribution.  It is blocked by the following on my PiHole

Exact matches for res.cloudinary.com found in:
   https://adblock.mahakala.is
   https://hostsfile.mine.nu/hosts0.txt
   https://tspprs.com/dl/cl1
   https://tspprs.com/dl/phishing

White-listing it allowed for the images on (in my case) bookings.gatwickairport.com to be shown correctly.  Please can you confirm and white-list if appropriate?

Thanks

Matt

**Comment by anudeepND** [comment]
@mc9662 Thanks for bringing it my notice. It is now added
