### ISSUE TITLE
Consider adding fontawesome.com hosts to the whitelist

### ISSUE THREAD

**Issue by lightswitch05** [anudeepND/whitelist#59]
Hello,

Would you consider adding `pro.fontawesome.com` and `use.fontawesome.com` to your whitelist? I have issues with them being blocked at https://github.com/jawz101/MobileAdTrackers/issues/5

**Comment by anudeepND** [comment]
Sorry for the late response. Domains are now added to the list

**Comment by lightswitch05** [comment]
Thanks!

**Comment by jawz101** [comment]
hey lightswitch & anudeep - I went ahead and removed those 2 from my list shorty after the issue came up.  Sorry for my earlier griping @lightswitch05 https://github.com/jawz101/MobileAdTrackers

**Comment by lightswitch05** [comment]
Thanks for the update @jawz101- I’ve been known to get moody over my list as well 😆
