### ISSUE TITLE
Your curl command

### ISSUE THREAD

**Issue by sml156** [anudeepND/whitelist#6]
First off thanks for giving me the idea to store my White List for Pihole on GitHub.

I copy pasted your curl command into my GitHub page and it did not work as I expected. I expected it to overwrite my old whitelist.txt file

What it actually did was append the list to my old list and doubled the size with the same info I had before.

In your curl command at the end is " >> /etc/pihole/whitelist.txt "  # this appends the text to the end 

I had to change mine to " > /etc/pihole/whitelist.txt "  # this overwrites the whole file

your's >>

mine >

Your whitelist will get huge if you do this often.

**Comment by anudeepND** [comment]
Thanks for the interest @sml156, I have updated the repo, please take a look at README.
