### ISSUE TITLE
edgekey.net

### ISSUE THREAD

**Issue by QuiGonLeong** [anudeepND/whitelist#63]
This domain is for the Akamai CDN.

**Comment by anudeepND** [comment]
@QuiGonLeong It's not present in the default adlist, which host files are you using?

**Comment by QuiGonLeong** [comment]
Match found in https://v.firebog.net/hosts/static/w3kbl.txt:
   wildcard.moatads.com.edgekey.net
 Match found in https://v.firebog.net/hosts/AdguardDNS.txt:
   moatads.com.edgekey.net
   analytics.edgekey.net
 Match found in
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt:
   ma1310-r.analytics.edgekey.net
   ma312-r.analytics.edgekey.net
 Match found in https://hosts-file.net/ad_servers.txt:
   79423.analytics.edgekey.net
   ma180-r.analytics.edgekey.net
   ma728-r.analytics.edgekey.net

**Comment by anudeepND** [comment]
@QuiGonLeong These domains appear to be tracking domains, I will add `edgekey.net` if it is present in any host file.
