### ISSUE TITLE
gawk -i inplace '!a[$0]++' /etc/pihole/whitelist.txt not working on CentOS 7

### ISSUE THREAD

**Issue by Melantrix** [anudeepND/whitelist#66]
I just tried running your script on a fresh CentOS 7 OS. This fails (or does not run de deduplication part of the script) because gawk is an old version on CentOS (and is not updated yet in the repositories). this means that `gawk -i inplace '!a[$0]++' /etc/pihole/whitelist.txt` will not run or work. 

I have figured out that running `awk '!seen[$0]++' /etc/pihole/whitelist.txt` does work however. Maybe you can use this in the script for all distributions or add an if/switch for CentOs?

**Comment by anudeepND** [comment]
@Melantrix Thanks for bringing it to notice. It does need some testing on other ditros.

**Comment by anudeepND** [comment]
@Melantrix This issue is resolved in the latest version. Closing
