### ISSUE TITLE
netflix domains

### ISSUE THREAD

**Issue by xxcriticxx** [anudeepND/whitelist#69]
the following domains are needed for netflix to working correctly

can you please add this to `optional-list.txt` 

`api-global.netflix.com`
`ichnaea.netflix.com`
`appboot.netflix.com`
`secure.netflix.com`

**Comment by anudeepND** [comment]
@xxcriticxx Thanks for reporting, which host file block this domain?

**Comment by xxcriticxx** [comment]
@anudeepND out the four i only needed to add `ichnaea.netflix.com` to get Netflix to work on my Samsung TV 

`api-global.netflix.com` Perflyst SmartTV
`ichnaea.netflix.com` Perflyst SmartTV / AdguardDNS
`appboot.netflix.com` Perflyst SmartTV
`secure.netflix.com` Perflyst SmartTV

**Comment by anudeepND** [comment]
@xxcriticxx It is been added to the optional-list.txt Thanks for reporting
