### ISSUE TITLE
Mydealz.de uses partners.webmasterplan.com

### ISSUE THREAD

**Issue by ChriKn** [anudeepND/whitelist#71]
Adding partners.webmasterplan.com to the whitelist fixed mydealz.de for me.
Maybe this could be an addition ?

Thanks !

**Comment by anudeepND** [comment]
@ChriKn which host files are you using?

**Comment by ChriKn** [comment]
Hi @anudeepND, I usewhitelist.txt and refferal-sites.txt

**Comment by anudeepND** [comment]
@pahakalle Thanks for the info. @ChriKn What issues are you having with mydealz.de? Images not loading? or any other issues?

**Comment by anudeepND** [comment]
@ChriKn Sorry for the late response, I browsed mydealz.de for a few minutes with [ublock logger](https://github.com/gorhill/uBlock/wiki/The-logger) opened, `partners.webmasterplan.com` never appeared in the log. Am I missing something?

**Comment by ChriKn** [comment]
Have you tried to follow any of the "deals" I think it depends on the site hosting the deal, some using madrilapp others webmasterplan...
Thanks for the help, greatly appreciated
