### ISSUE TITLE
npr news 

### ISSUE THREAD

**Issue by xxcriticxx** [anudeepND/whitelist#72]
need to whitelist `npr-news.streaming.adswizz.com` if you want to listen to the morning news podcast

fyi this will play sponsor clip before your news 

`Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts:`
`npr-news.streaming.adswizz.com`

**Comment by anudeepND** [comment]
@xxcriticxx Can confirm. I saw this in a reddit post on r/pihole
