### ISSUE TITLE
Add fls-eu.amazon.com and fls-na.amazon.com for prime video to work

### ISSUE THREAD

**Issue by meepmeep** [anudeepND/whitelist#76]
Theses hosts are in https://hosts-file.net/ad_servers.txt, but they need to be accessed to watch something on amazon prime video.

Could you add them ? (fls-eu.amazon.com and fls-na.amazon.com )

**Comment by xxcriticxx** [comment]
@meepmeep on what device you having trouble viewing prime?

**Comment by meepmeep** [comment]
I'm using chrome 71 on win10.
When launching a video, it stopped after 5~8sec, but if I whitelist theses url, it works (eu for europe, and na for north america)

`21:03:04 dnsmasq[421]: query[A] fls-eu.amazon.com from 192.168.1.41      ` 

Some analysis : 
https://discourse.pi-hole.net/t/fls-na-amazon-com-top-blocked-domain/5546/5
https://www.reddit.com/r/pihole/comments/9ex5rg/amazon_prime_video/

**Comment by xxcriticxx** [comment]
chrome 71 on win7 prime video works 

tomorrow i will test on win10

**Comment by anudeepND** [comment]
@meepmeep Amazon Prime android app and web app are working fine with these domain blocked (including fls-in.amazon.com blocked)

**Comment by mschoettle** [comment]
It breaks Amazon Prime on Apple TV. You can browse and select a video, but when starting one the loading icon stays there forever.
