### ISSUE TITLE
Additional referral sites

### ISSUE THREAD

**Issue by XelNika** [anudeepND/whitelist#78]
I've come across a few referral domains that I thought you might want. These are mainly from using [Pricerunner](https://en.wikipedia.org/wiki/PriceRunner) and Google:
```
#Pricerunner redirect
clk.tradedoubler.com
tc.tradetracker.com
track.adform.net
track.webgains.com

#CDON redirect (don't remember, either from marketing email or one of the two other categories)
solutions.tradedoubler.com

#Google shopping redirect
ad.atdmt.com
clickserve.dartsearch.net
```

**Comment by anudeepND** [comment]
> #Google shopping redirect 
ad.atdmt.com
clickserve.dartsearch.net

Are you referring to product links that appears on search page?

**Comment by XelNika** [comment]
Yes.

**Comment by anudeepND** [comment]
Thanks @XelNika
