### ISSUE TITLE
openload.co

### ISSUE THREAD

**Issue by xxcriticxx** [anudeepND/whitelist#83]
Match found in https://hosts-file.net/emd.txt:
   openload.co
   www.openload.co

**Comment by anudeepND** [comment]
But openload loads a ton of ad domains and redirects to many shady sites. I think it is better to leave it blocked

**Comment by xxcriticxx** [comment]
But you need it if you use Kodi

**Comment by anudeepND** [comment]
@xxcriticxx I will add it to optional list
