### ISSUE TITLE
Cannot login to groupme.com

### ISSUE THREAD

**Issue by chado99** [anudeepND/whitelist#84]
unable to login to the web client of groupme (https://web.groupme.com/signin) without first whitlisting: d2wy8f7a9ursnm.cloudfront.net
-- | --

**Comment by anudeepND** [comment]
@chado99 I will look into it. Thanks for reporting

**Comment by chado99** [comment]
Match found in https://hosts-file.net/ad_servers.txt:
   d2wy8f7a9ursnm.cloudfront.net

**Comment by anudeepND** [comment]
@chado99 Full URL is ​https://d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js, bugsnag is a error reporting tool, are you sure about this domain?

**Comment by chado99** [comment]
Interesting. Thank you. Let me look again.

**Comment by chado99** [comment]
pls close this issue.. My issue logging in was likely something else
