### ISSUE TITLE
Shopping sites blocked

### ISSUE THREAD

**Issue by chado99** [anudeepND/whitelist#85]
Unable to shop on sites driven by Mssl.com platform. Pls whitelist this domain and www.mssl.com.

**Comment by anudeepND** [comment]
@chado99 Please mention the host file in which it is blocked

**Comment by chado99** [comment]
Newbie question. Is there an easy way in PiHole to check which hostile is impacting?

**Comment by anudeepND** [comment]
@chado99 Go to http://pi.hole/admin/queryads.php and search the domain

**Comment by chado99** [comment]
Match found in https://hosts-file.net/ad_servers.txt:
   mcssl.com
   www.mcssl.com

**Comment by chado99** [comment]
My specific use case was trying a user was trying to shop on the https://www.precisionnutrition.com/ which uses mcssl.com anytime you try to add a book/product to the cart and checkout.

**Comment by anudeepND** [comment]
@chado99 This issue is addressed here: https://forums.malwarebytes.com/topic/242854-shopping-cart-blocked/

**Comment by chado99** [comment]
Thanks!
