### ISSUE TITLE
Check llnwd.net subdomains for the white list

### ISSUE THREAD

**Issue by ZeroDot1** [anudeepND/whitelist#86]
Download: [llnwd.net.txt](https://github.com/anudeepND/whitelist/files/2853664/llnwd.net.txt) Subdomain List
Please check the document with the URLs, and check which URLs can be on the white list.
e.g. Amazon Video and BBC Radio are distributed via subdomains.
Unfortunately, this is not included in most White Lists.
Maybe you should create an extra list with only subdomains from this CDN.

**Comment by anudeepND** [comment]
@ZeroDot1 11K domains is a lot. Best case is to cherry pick the required ones and adding them to the list.
