### ISSUE TITLE
developers.google.com for whitelist

### ISSUE THREAD

**Issue by chado99** [anudeepND/whitelist#87]
developers.google.com is a common site for referencing google documentation.

**Comment by anudeepND** [comment]
@chado99 Can you mention the host files which block this domain?

**Comment by chado99** [comment]
Match found in https://tspprs.com/dl/tracking:
   developers.google.com

**Comment by chado99** [comment]
I have stopped using the tspprs.com blacklists because of too many false positives. perhaps others have a similar experieince.

**Comment by anudeepND** [comment]
@chado99 tspprs.com does block a lot of legit domains, I have seen some reddit posts too
