### ISSUE TITLE
Some videos blocked from huffingtonpost

### ISSUE THREAD

**Issue by chado99** [anudeepND/whitelist#90]
First video on this page blocked. https://m.huffpost.com/us/entry/us_5c6a1dc5e4b05c889d20661d?ncid=APPLENEWS00001

Whitelist

   hlsrv.vidible.tv

 Match found in https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt:
   hlsrv.vidible.tv

**Comment by anudeepND** [comment]
@chado99 oops it's present in my own host file xD, I will remove it ASAP

**Comment by anudeepND** [comment]
Thanks @chado99
