### ISSUE TITLE
optional-list: Spotify urls to be able to cast to Denon Heos speakers

### ISSUE THREAD

**Issue by adrianvg** [anudeepND/whitelist#93]
Hi,

Connecting to Spotify Premium from mobile phone works using these white-listings:

mobile-ap.spotify.com
apresolve.spotify.com
upgrade.scdn.com
market.spotify.com
spclient.wg.spotify.com

To be able to connect/cast to Denon Heos wifi-speakers from within Spotify, this needed to be added as well:
audio-ake.spotify.com.edgesuite.net

I'm thinking more wifi-speaker brands may need the last white listing as well.
Use these at your own discretion.

Excerpts from my pihole log below.
192.168.0.111 is one of the wifi-speakers.

```
Mar  2 19:43:32 dnsmasq[15004]: query[A] audio-ake.spotify.com.edgesuite.net from 192.168.0.111
Mar  2 19:43:32 dnsmasq[15004]: /etc/pihole/gravity.list audio-ake.spotify.com.edgesuite.net is 192.168.0.10
Mar  2 19:43:32 dnsmasq[15004]: query[AAAA] audio-ake.spotify.com.edgesuite.net from 192.168.0.111
Mar  2 19:43:32 dnsmasq[15004]: /etc/pihole/gravity.list audio-ake.spotify.com.edgesuite.net is ::
```

//AvG

**Comment by anudeepND** [comment]
@adrianvg Which blocklist are you using?

**Comment by anudeepND** [comment]
@adrianvg Thanks for reporting

**Comment by planet0** [comment]
Hi @anudeepND, I was looking through the optional-list.txt and noticed a small typo relating to this.

Currently is audio-ake.spotify.com.edgesuite **.ne** in the txt file, should be edgesuite **.net** at the end.

**Comment by anudeepND** [comment]
@planet0 oh thanks! I will fix it when I get home
