### ISSUE TITLE
Whitelisting Disqus

### ISSUE THREAD

**Issue by adrianvg** [anudeepND/whitelist#95]
Hi AnuDeep!

Consider adding these hostnames in order to whitelist Disqus.

disqus.com
disquscdn.com
prod.disqus.map.fastlylb.net
c.disquscdn.com.cdn.cloudflare.net
referrer.disqus.com

Cheers,
AvG

**Comment by anudeepND** [comment]
@adrianvg Can you mention the host files which blocks these domains?

**Comment by adrianvg** [comment]
No idea, these are the lists I currently use:

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list_browser.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list_optional.txt
https://easylist.to/easylist/fanboy-annoyance.txt
https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
https://raw.githubusercontent.com/chadmayfield/pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list
https://dbl.oisd.nl

**Comment by patrickdrd** [comment]
you can download them one by one naming each one carefully and then searching with find in files and
after you find which list has it, you should report it to the appropriate list,
that's what I do when I find there's something going wrong

**Comment by adrianvg** [comment]
I'll see what I can do. Thanks for the hint!

**Comment by patrickdrd** [comment]
I downloaded energized and stevenblack myself and I didn't find any for the domains you reported,
especially energized, since you use the ultimate, it would be a culrpit, but it's not the one,
you would rather maintain your own whitelist, that 's what I do and it's close to 2000 entries!

**Comment by anudeepND** [comment]
@adrianvg https://easylist-downloads.adblockplus.org/antiadblockfilters.txt and https://easylist.to/easylist/fanboy-annoyance.txt are not compatible with Pi-Hole, these list are for browser adblockers like uBlock and Adblock Plus. Remove them and check.
After removing them, you can search the domains with `pihole -q disqus.com`. As @patrickdrd said  energized ultimate might be the culprit

**Comment by adrianvg** [comment]
@anudeepND 
I know, I meant to remove them, but never got around to it after I initially set up pihole.
Time to do it now!

**Comment by adrianvg** [comment]
Removed the lists mentioned above.
Running "pihole -q disqus.com" reveals there are plenty of other blacklists referring to *.disqus.com.
No matter, I've whitelisted the important disqus sites as stated initially.
Thanks for the feedback!

**Comment by anudeepND** [comment]
@adrianvg referrer.disqus.com might be a tracking domain (?). I have default adlist and https://github.com/anudeepND/blacklist which is maintained by me, I don't have any problems with any of the Disqus service
