### ISSUE TITLE
Whitelists required to download firestick apps

### ISSUE THREAD

**Issue by Thomas499** [anudeepND/whitelist#96]
**Whitelist Request:**
mas-ext.amazon.com

**Devices effected:** 
All amazon firesticks

**Hosts list that include mas-ext.amazon.com:**
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts.txt

**Effects of having list above enabled without mas-ext.amazon.com on whitelist:**
When user tries to download any new app on firestick from official app store this will pop up
![image](https://user-images.githubusercontent.com/38442058/54689992-bb2c9600-4add-11e9-8d7c-1a7c021a39d5.png)
Can not download apps on firestick

**Effects of whitelisting:**
![image](https://user-images.githubusercontent.com/38442058/54690090-edd68e80-4add-11e9-9551-27340241d853.png)
Can download apps on firestick

**Comment by anudeepND** [comment]
Fixed
