### ISSUE TITLE
Suggestion: Docker support

### ISSUE THREAD

**Issue by johnfc2018** [anudeepND/whitelist#97]
Hi,

I like how your script gets the whitelist.txt and adds anything that is missing from the existing whitelist. However, here is a couple of changes you might want to make. 

Add command line arguments such as:
./whitelist.sh docker dockername /path/to/etc/pihole 

So if your script sees the argument "docker" it calls docker exec dockername pihole -g >/dev/null and if not, it runs normally.

**Comment by flodus** [comment]
I'm interesting to have this feature, whitelist for pihole docker. I don't know how to install your lists on my pihole container.

**Comment by pahakalle** [comment]
I don't see any reason to add docker support directly to the script as it's easy to run it with something like `docker exec mycontainer /path/to/whitelist.sh
`

Instructions for that could be added to the readme toug.

**Comment by anudeepND** [comment]
@johnfc2018 Can you check with the latest version of this repo? I tested with my pihole/pihole docker image and it works fine.
